\set ON_ERROR_STOP on

DO $roles$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'tme_owner') THEN
        CREATE ROLE tme_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'tme_migrator') THEN
        CREATE ROLE tme_migrator LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'tme_runtime') THEN
        CREATE ROLE tme_runtime LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'tme_auth') THEN
        CREATE ROLE tme_auth LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'tme_backup') THEN
        CREATE ROLE tme_backup LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE REPLICATION NOBYPASSRLS;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'tme_monitor') THEN
        CREATE ROLE tme_monitor LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
    END IF;
END
$roles$;

GRANT tme_owner TO tme_migrator;
REVOKE ALL ON DATABASE tme FROM PUBLIC;
GRANT CONNECT ON DATABASE tme TO tme_owner, tme_migrator, tme_runtime, tme_auth, tme_backup, tme_monitor;
GRANT pg_monitor TO tme_monitor;
GRANT EXECUTE ON FUNCTION pg_catalog.pg_control_system() TO tme_runtime;
