//! First-expedition geography accepted on 2026-09-06, with the owner's
//! temple-layout amendment on 2026-09-07.
//! The review and encoding receipt are documented in the land README.
use super::*;

const MAP_PROPERTIES: &[(&str, PropertyValue)] = &[
    (
        "artifact_status",
        PropertyValue::Text("tracked_authored_land"),
    ),
    (
        "authoring_origin",
        PropertyValue::Text("accepted_geography_encoding"),
    ),
    (
        "content_authority",
        PropertyValue::Text("authored_geography"),
    ),
    ("envelope_locked", PropertyValue::Flag(true)),
    ("runtime_consumable", PropertyValue::Flag(true)),
];

pub static LAND: LandContract = LandContract {
    reviewed_encoding: Some(ReviewedEncoding {
        review_manifest_sha256: "d132d434d60e20d15b2962834bfde80e6bd04d8cf8d01da615674c297dee8d73",
        geography_sha256: "2ce205b35536006932437c855827575d26f61a26813ade0bc885160db95534d4",
    }),
    id: "first_expedition",
    realm_id: "first_expedition",
    realm_name: "First Land",
    arrival_id: "dock_arrival",
    members: &[
        MemberContract {
            id: "arrival",
            document: "content/lands/first-expedition/arrival.tmj",
            width: 27,
            height: 36,
            classes: &[
                base("expedition_water", true),
                base("expedition_grass", false),
                base("expedition_forest", false),
                base("expedition_sand", false),
                base("expedition_rock", true),
                base("expedition_town_ground", false),
                class("expedition_path", TileRole::Route),
                class("expedition_bridge", TileRole::Route),
                class("expedition_footprint", TileRole::Footprint),
                class("expedition_mark", TileRole::Mark),
                class(
                    "expedition_blocked",
                    TileRole::Passability { walkable: false },
                ),
                class(
                    "expedition_walkable",
                    TileRole::Passability { walkable: true },
                ),
                base("expedition_prop_occupancy", true),
            ],
            tile_layers: &[
                "base_terrain",
                "routes",
                "structure_footprints",
                "landmark_marks",
                "passability",
            ],
            object_layers: &["structures", "transitions", "landmarks"],
            map_properties: MAP_PROPERTIES,
            structures: &[
                StructureContract {
                    id: "arrival_1",
                    scope: "clustered",
                },
                StructureContract {
                    id: "arrival_10",
                    scope: "clustered",
                },
                StructureContract {
                    id: "arrival_2",
                    scope: "clustered",
                },
                StructureContract {
                    id: "arrival_3",
                    scope: "clustered",
                },
                StructureContract {
                    id: "arrival_4",
                    scope: "clustered",
                },
                StructureContract {
                    id: "arrival_5",
                    scope: "clustered",
                },
                StructureContract {
                    id: "arrival_6",
                    scope: "clustered",
                },
                StructureContract {
                    id: "arrival_7",
                    scope: "clustered",
                },
                StructureContract {
                    id: "arrival_8",
                    scope: "clustered",
                },
                StructureContract {
                    id: "arrival_9",
                    scope: "clustered",
                },
            ],
            landmarks: &[LandmarkContract {
                id: "arrival",
                role: "arrival",
                marker_class: "",
            }],
            transitions: &[
                TransitionContract {
                    layout: TransitionLayout::Threshold,
                    id: "arrival_to_lodge",
                    target_member: "lodge",
                    paired_transition: "lodge_to_arrival",
                    direction: "passage",
                    marker_class: "",
                },
                TransitionContract {
                    layout: TransitionLayout::Threshold,
                    id: "arrival_to_bank",
                    target_member: "bank",
                    paired_transition: "bank_to_arrival",
                    direction: "passage",
                    marker_class: "",
                },
                TransitionContract {
                    layout: TransitionLayout::Threshold,
                    id: "arrival_to_outfitter",
                    target_member: "outfitter",
                    paired_transition: "outfitter_to_arrival",
                    direction: "passage",
                    marker_class: "",
                },
                TransitionContract {
                    layout: TransitionLayout::Threshold,
                    id: "arrival_to_market",
                    target_member: "market",
                    paired_transition: "market_to_arrival",
                    direction: "passage",
                    marker_class: "",
                },
                TransitionContract {
                    layout: TransitionLayout::Threshold,
                    id: "arrival_to_bakery",
                    target_member: "bakery",
                    paired_transition: "bakery_to_arrival",
                    direction: "passage",
                    marker_class: "",
                },
                TransitionContract {
                    layout: TransitionLayout::Threshold,
                    id: "arrival_to_herbalist",
                    target_member: "herbalist",
                    paired_transition: "herbalist_to_arrival",
                    direction: "passage",
                    marker_class: "",
                },
                TransitionContract {
                    layout: TransitionLayout::Threshold,
                    id: "arrival_to_forge",
                    target_member: "forge",
                    paired_transition: "forge_to_arrival",
                    direction: "passage",
                    marker_class: "",
                },
                TransitionContract {
                    layout: TransitionLayout::Threshold,
                    id: "arrival_to_chandler",
                    target_member: "chandler",
                    paired_transition: "chandler_to_arrival",
                    direction: "passage",
                    marker_class: "",
                },
                TransitionContract {
                    layout: TransitionLayout::Threshold,
                    id: "arrival_to_temple",
                    target_member: "temple",
                    paired_transition: "temple_to_arrival",
                    direction: "passage",
                    marker_class: "",
                },
                TransitionContract {
                    layout: TransitionLayout::Threshold,
                    id: "arrival_to_trainers",
                    target_member: "trainers",
                    paired_transition: "trainers_to_arrival",
                    direction: "passage",
                    marker_class: "",
                },
            ],
            clustered_ground_class: Some("expedition_town_ground"),
            wall_terrain_ids: &[],
            presentation: LevelPresentation {
                scene_role: SceneRoleDef::Overworld,
                presentation_mode: PresentationModeDef::OverworldTown,
                law_zone: LawZoneDef::None,
                world_zoom: WorldZoomDef {
                    screen_cell_pitch: [156, 104],
                },
                staged_viewport: None,
            },
            candidate_entry: true,
        },
        MemberContract {
            id: "lodge",
            document: "content/lands/first-expedition/lodge.tmj",
            width: 7,
            height: 4,
            classes: &[
                base("expedition_floor", false),
                base("expedition_furniture", true),
                base("expedition_void", true),
                class(
                    "expedition_blocked",
                    TileRole::Passability { walkable: false },
                ),
                class(
                    "expedition_walkable",
                    TileRole::Passability { walkable: true },
                ),
            ],
            tile_layers: &[
                "base_terrain",
                "routes",
                "structure_footprints",
                "landmark_marks",
                "passability",
            ],
            object_layers: &["structures", "transitions", "landmarks"],
            map_properties: MAP_PROPERTIES,
            structures: &[],
            landmarks: &[],
            transitions: &[TransitionContract {
                layout: TransitionLayout::Threshold,
                id: "lodge_to_arrival",
                target_member: "arrival",
                paired_transition: "arrival_to_lodge",
                direction: "passage",
                marker_class: "",
            }],
            clustered_ground_class: None,
            wall_terrain_ids: &[],
            presentation: LevelPresentation {
                scene_role: SceneRoleDef::Interior,
                presentation_mode: PresentationModeDef::OverworldTown,
                law_zone: LawZoneDef::None,
                world_zoom: WorldZoomDef {
                    screen_cell_pitch: [156, 104],
                },
                staged_viewport: Some(StagedViewportDef {
                    frame_size: [1920, 1080],
                    fit_whole_level: true,
                }),
            },
            candidate_entry: false,
        },
        MemberContract {
            id: "bank",
            document: "content/lands/first-expedition/bank.tmj",
            width: 5,
            height: 4,
            classes: &[
                base("expedition_floor", false),
                base("expedition_furniture", true),
                base("expedition_void", true),
                class(
                    "expedition_blocked",
                    TileRole::Passability { walkable: false },
                ),
                class(
                    "expedition_walkable",
                    TileRole::Passability { walkable: true },
                ),
            ],
            tile_layers: &[
                "base_terrain",
                "routes",
                "structure_footprints",
                "landmark_marks",
                "passability",
            ],
            object_layers: &["structures", "transitions", "landmarks"],
            map_properties: MAP_PROPERTIES,
            structures: &[],
            landmarks: &[],
            transitions: &[TransitionContract {
                layout: TransitionLayout::Threshold,
                id: "bank_to_arrival",
                target_member: "arrival",
                paired_transition: "arrival_to_bank",
                direction: "passage",
                marker_class: "",
            }],
            clustered_ground_class: None,
            wall_terrain_ids: &[],
            presentation: LevelPresentation {
                scene_role: SceneRoleDef::Interior,
                presentation_mode: PresentationModeDef::OverworldTown,
                law_zone: LawZoneDef::None,
                world_zoom: WorldZoomDef {
                    screen_cell_pitch: [156, 104],
                },
                staged_viewport: Some(StagedViewportDef {
                    frame_size: [1920, 1080],
                    fit_whole_level: true,
                }),
            },
            candidate_entry: false,
        },
        MemberContract {
            id: "outfitter",
            document: "content/lands/first-expedition/outfitter.tmj",
            width: 4,
            height: 4,
            classes: &[
                base("expedition_floor", false),
                base("expedition_furniture", true),
                base("expedition_void", true),
                class(
                    "expedition_blocked",
                    TileRole::Passability { walkable: false },
                ),
                class(
                    "expedition_walkable",
                    TileRole::Passability { walkable: true },
                ),
            ],
            tile_layers: &[
                "base_terrain",
                "routes",
                "structure_footprints",
                "landmark_marks",
                "passability",
            ],
            object_layers: &["structures", "transitions", "landmarks"],
            map_properties: MAP_PROPERTIES,
            structures: &[],
            landmarks: &[],
            transitions: &[TransitionContract {
                layout: TransitionLayout::Threshold,
                id: "outfitter_to_arrival",
                target_member: "arrival",
                paired_transition: "arrival_to_outfitter",
                direction: "passage",
                marker_class: "",
            }],
            clustered_ground_class: None,
            wall_terrain_ids: &[],
            presentation: LevelPresentation {
                scene_role: SceneRoleDef::Interior,
                presentation_mode: PresentationModeDef::OverworldTown,
                law_zone: LawZoneDef::None,
                world_zoom: WorldZoomDef {
                    screen_cell_pitch: [156, 104],
                },
                staged_viewport: Some(StagedViewportDef {
                    frame_size: [1920, 1080],
                    fit_whole_level: true,
                }),
            },
            candidate_entry: false,
        },
        MemberContract {
            id: "market",
            document: "content/lands/first-expedition/market.tmj",
            width: 4,
            height: 2,
            classes: &[
                base("expedition_floor", false),
                base("expedition_furniture", true),
                base("expedition_void", true),
                class(
                    "expedition_blocked",
                    TileRole::Passability { walkable: false },
                ),
                class(
                    "expedition_walkable",
                    TileRole::Passability { walkable: true },
                ),
            ],
            tile_layers: &[
                "base_terrain",
                "routes",
                "structure_footprints",
                "landmark_marks",
                "passability",
            ],
            object_layers: &["structures", "transitions", "landmarks"],
            map_properties: MAP_PROPERTIES,
            structures: &[],
            landmarks: &[],
            transitions: &[TransitionContract {
                layout: TransitionLayout::Threshold,
                id: "market_to_arrival",
                target_member: "arrival",
                paired_transition: "arrival_to_market",
                direction: "passage",
                marker_class: "",
            }],
            clustered_ground_class: None,
            wall_terrain_ids: &[],
            presentation: LevelPresentation {
                scene_role: SceneRoleDef::Interior,
                presentation_mode: PresentationModeDef::OverworldTown,
                law_zone: LawZoneDef::None,
                world_zoom: WorldZoomDef {
                    screen_cell_pitch: [156, 104],
                },
                staged_viewport: Some(StagedViewportDef {
                    frame_size: [1920, 1080],
                    fit_whole_level: true,
                }),
            },
            candidate_entry: false,
        },
        MemberContract {
            id: "bakery",
            document: "content/lands/first-expedition/bakery.tmj",
            width: 3,
            height: 3,
            classes: &[
                base("expedition_floor", false),
                base("expedition_furniture", true),
                base("expedition_void", true),
                class(
                    "expedition_blocked",
                    TileRole::Passability { walkable: false },
                ),
                class(
                    "expedition_walkable",
                    TileRole::Passability { walkable: true },
                ),
            ],
            tile_layers: &[
                "base_terrain",
                "routes",
                "structure_footprints",
                "landmark_marks",
                "passability",
            ],
            object_layers: &["structures", "transitions", "landmarks"],
            map_properties: MAP_PROPERTIES,
            structures: &[],
            landmarks: &[],
            transitions: &[TransitionContract {
                layout: TransitionLayout::Threshold,
                id: "bakery_to_arrival",
                target_member: "arrival",
                paired_transition: "arrival_to_bakery",
                direction: "passage",
                marker_class: "",
            }],
            clustered_ground_class: None,
            wall_terrain_ids: &[],
            presentation: LevelPresentation {
                scene_role: SceneRoleDef::Interior,
                presentation_mode: PresentationModeDef::OverworldTown,
                law_zone: LawZoneDef::None,
                world_zoom: WorldZoomDef {
                    screen_cell_pitch: [156, 104],
                },
                staged_viewport: Some(StagedViewportDef {
                    frame_size: [1920, 1080],
                    fit_whole_level: true,
                }),
            },
            candidate_entry: false,
        },
        MemberContract {
            id: "herbalist",
            document: "content/lands/first-expedition/herbalist.tmj",
            width: 4,
            height: 3,
            classes: &[
                base("expedition_floor", false),
                base("expedition_furniture", true),
                base("expedition_void", true),
                class(
                    "expedition_blocked",
                    TileRole::Passability { walkable: false },
                ),
                class(
                    "expedition_walkable",
                    TileRole::Passability { walkable: true },
                ),
            ],
            tile_layers: &[
                "base_terrain",
                "routes",
                "structure_footprints",
                "landmark_marks",
                "passability",
            ],
            object_layers: &["structures", "transitions", "landmarks"],
            map_properties: MAP_PROPERTIES,
            structures: &[],
            landmarks: &[],
            transitions: &[TransitionContract {
                layout: TransitionLayout::Threshold,
                id: "herbalist_to_arrival",
                target_member: "arrival",
                paired_transition: "arrival_to_herbalist",
                direction: "passage",
                marker_class: "",
            }],
            clustered_ground_class: None,
            wall_terrain_ids: &[],
            presentation: LevelPresentation {
                scene_role: SceneRoleDef::Interior,
                presentation_mode: PresentationModeDef::OverworldTown,
                law_zone: LawZoneDef::None,
                world_zoom: WorldZoomDef {
                    screen_cell_pitch: [156, 104],
                },
                staged_viewport: Some(StagedViewportDef {
                    frame_size: [1920, 1080],
                    fit_whole_level: true,
                }),
            },
            candidate_entry: false,
        },
        MemberContract {
            id: "forge",
            document: "content/lands/first-expedition/forge.tmj",
            width: 4,
            height: 3,
            classes: &[
                base("expedition_floor", false),
                base("expedition_furniture", true),
                base("expedition_void", true),
                class(
                    "expedition_blocked",
                    TileRole::Passability { walkable: false },
                ),
                class(
                    "expedition_walkable",
                    TileRole::Passability { walkable: true },
                ),
            ],
            tile_layers: &[
                "base_terrain",
                "routes",
                "structure_footprints",
                "landmark_marks",
                "passability",
            ],
            object_layers: &["structures", "transitions", "landmarks"],
            map_properties: MAP_PROPERTIES,
            structures: &[],
            landmarks: &[],
            transitions: &[TransitionContract {
                layout: TransitionLayout::Threshold,
                id: "forge_to_arrival",
                target_member: "arrival",
                paired_transition: "arrival_to_forge",
                direction: "passage",
                marker_class: "",
            }],
            clustered_ground_class: None,
            wall_terrain_ids: &[],
            presentation: LevelPresentation {
                scene_role: SceneRoleDef::Interior,
                presentation_mode: PresentationModeDef::OverworldTown,
                law_zone: LawZoneDef::None,
                world_zoom: WorldZoomDef {
                    screen_cell_pitch: [156, 104],
                },
                staged_viewport: Some(StagedViewportDef {
                    frame_size: [1920, 1080],
                    fit_whole_level: true,
                }),
            },
            candidate_entry: false,
        },
        MemberContract {
            id: "chandler",
            document: "content/lands/first-expedition/chandler.tmj",
            width: 4,
            height: 3,
            classes: &[
                base("expedition_floor", false),
                base("expedition_furniture", true),
                base("expedition_void", true),
                class(
                    "expedition_blocked",
                    TileRole::Passability { walkable: false },
                ),
                class(
                    "expedition_walkable",
                    TileRole::Passability { walkable: true },
                ),
            ],
            tile_layers: &[
                "base_terrain",
                "routes",
                "structure_footprints",
                "landmark_marks",
                "passability",
            ],
            object_layers: &["structures", "transitions", "landmarks"],
            map_properties: MAP_PROPERTIES,
            structures: &[],
            landmarks: &[],
            transitions: &[TransitionContract {
                layout: TransitionLayout::Threshold,
                id: "chandler_to_arrival",
                target_member: "arrival",
                paired_transition: "arrival_to_chandler",
                direction: "passage",
                marker_class: "",
            }],
            clustered_ground_class: None,
            wall_terrain_ids: &[],
            presentation: LevelPresentation {
                scene_role: SceneRoleDef::Interior,
                presentation_mode: PresentationModeDef::OverworldTown,
                law_zone: LawZoneDef::None,
                world_zoom: WorldZoomDef {
                    screen_cell_pitch: [156, 104],
                },
                staged_viewport: Some(StagedViewportDef {
                    frame_size: [1920, 1080],
                    fit_whole_level: true,
                }),
            },
            candidate_entry: false,
        },
        MemberContract {
            id: "temple",
            document: "content/lands/first-expedition/temple.tmj",
            width: 7,
            height: 8,
            classes: &[
                base("expedition_floor", false),
                base("expedition_furniture", true),
                base("expedition_void", true),
                class(
                    "expedition_blocked",
                    TileRole::Passability { walkable: false },
                ),
                class(
                    "expedition_walkable",
                    TileRole::Passability { walkable: true },
                ),
            ],
            tile_layers: &[
                "base_terrain",
                "routes",
                "structure_footprints",
                "landmark_marks",
                "passability",
            ],
            object_layers: &["structures", "transitions", "landmarks"],
            map_properties: MAP_PROPERTIES,
            structures: &[],
            landmarks: &[],
            transitions: &[
                TransitionContract {
                    layout: TransitionLayout::Threshold,
                    id: "temple_to_arrival",
                    target_member: "arrival",
                    paired_transition: "arrival_to_temple",
                    direction: "passage",
                    marker_class: "",
                },
                TransitionContract {
                    layout: TransitionLayout::Threshold,
                    id: "temple_to_d1_entry",
                    target_member: "d1_entry",
                    paired_transition: "d1_entry_to_temple",
                    direction: "down",
                    marker_class: "",
                },
            ],
            clustered_ground_class: None,
            wall_terrain_ids: &[],
            presentation: LevelPresentation {
                scene_role: SceneRoleDef::Interior,
                presentation_mode: PresentationModeDef::OverworldTown,
                law_zone: LawZoneDef::None,
                world_zoom: WorldZoomDef {
                    screen_cell_pitch: [156, 104],
                },
                staged_viewport: Some(StagedViewportDef {
                    frame_size: [1920, 1080],
                    fit_whole_level: true,
                }),
            },
            candidate_entry: false,
        },
        MemberContract {
            id: "trainers",
            document: "content/lands/first-expedition/trainers.tmj",
            width: 8,
            height: 5,
            classes: &[
                base("expedition_floor", false),
                base("expedition_furniture", true),
                base("expedition_void", true),
                class(
                    "expedition_blocked",
                    TileRole::Passability { walkable: false },
                ),
                class(
                    "expedition_walkable",
                    TileRole::Passability { walkable: true },
                ),
            ],
            tile_layers: &[
                "base_terrain",
                "routes",
                "structure_footprints",
                "landmark_marks",
                "passability",
            ],
            object_layers: &["structures", "transitions", "landmarks"],
            map_properties: MAP_PROPERTIES,
            structures: &[],
            landmarks: &[],
            transitions: &[TransitionContract {
                layout: TransitionLayout::Threshold,
                id: "trainers_to_arrival",
                target_member: "arrival",
                paired_transition: "arrival_to_trainers",
                direction: "passage",
                marker_class: "",
            }],
            clustered_ground_class: None,
            wall_terrain_ids: &[],
            presentation: LevelPresentation {
                scene_role: SceneRoleDef::Interior,
                presentation_mode: PresentationModeDef::OverworldTown,
                law_zone: LawZoneDef::None,
                world_zoom: WorldZoomDef {
                    screen_cell_pitch: [156, 104],
                },
                staged_viewport: Some(StagedViewportDef {
                    frame_size: [1920, 1080],
                    fit_whole_level: true,
                }),
            },
            candidate_entry: false,
        },
        MemberContract {
            id: "d1_entry",
            document: "content/lands/first-expedition/d1_entry.tmj",
            width: 7,
            height: 7,
            classes: &[
                base("expedition_wall", true),
                base("expedition_floor", false),
                base("expedition_closed_door", true),
                base("expedition_deferred", true),
                class("expedition_path", TileRole::Route),
                class("expedition_footprint", TileRole::Footprint),
                class("expedition_mark", TileRole::Mark),
                class(
                    "expedition_blocked",
                    TileRole::Passability { walkable: false },
                ),
                class(
                    "expedition_walkable",
                    TileRole::Passability { walkable: true },
                ),
            ],
            tile_layers: &[
                "base_terrain",
                "routes",
                "structure_footprints",
                "landmark_marks",
                "passability",
            ],
            object_layers: &["structures", "transitions", "landmarks"],
            map_properties: MAP_PROPERTIES,
            structures: &[],
            landmarks: &[],
            transitions: &[TransitionContract {
                layout: TransitionLayout::Threshold,
                id: "d1_entry_to_temple",
                target_member: "temple",
                paired_transition: "temple_to_d1_entry",
                direction: "up",
                marker_class: "",
            }],
            clustered_ground_class: None,
            wall_terrain_ids: &[
                "expedition_wall",
                "expedition_closed_door",
                "expedition_deferred",
            ],
            presentation: LevelPresentation {
                scene_role: SceneRoleDef::Interior,
                presentation_mode: PresentationModeDef::OverworldTown,
                law_zone: LawZoneDef::None,
                world_zoom: WorldZoomDef {
                    screen_cell_pitch: [156, 104],
                },
                staged_viewport: Some(StagedViewportDef {
                    frame_size: [1920, 1080],
                    fit_whole_level: true,
                }),
            },
            candidate_entry: false,
        },
    ],
    receipt_path: "content/lands/first-expedition/promotion.json",
    receipt_kind: "authored_land_promotion",
    receipt_status: "owner_accepted_first_expedition_geography",
    receipt_attested_by: "peter",
    receipt_attested_on: "2026-09-07",
    master_digest: "7e37e586161c2b8d6c9f46f3eb154d5697e0acc12a42ca6bd26217cf07c419e9",
    authority: ReceiptAuthority {
        coordinates: true,
        terrain_and_passability: true,
        structures_and_landmarks: true,
        member_transition_endpoints: true,
        runtime_loads_authoring_source: true,
        presentation_art: false,
        gameplay_tuning: false,
        content_canon: false,
    },
    world_template_output: "content/lands/first-expedition/generated/world_template.json",
    report_output: "content/lands/first-expedition/generated/compile_report.json",
    workbench_projection_output: "content/lands/first-expedition/generated/workbench_projection.json",
    terrain_registry_catalog: "content/lands/first-expedition/catalog.json",
    terrain_registry_profile: "profile/first_expedition",
};
