pub const SNAPSHOT_CONTRACT_VERSION: u32 = 31;
pub const OBSERVED_SNAPSHOT_CONTRACT_VERSION: u32 = 30;
pub const EVENT_CONTRACT_VERSION: u32 = 41;
pub const ACTION_CONTEXT_CONTRACT_VERSION: u32 = 32;
pub const PATH_PREVIEW_CONTRACT_VERSION: u32 = 8;
pub const TRACE_CONTRACT_VERSION: u32 = 1;
pub const TRACE_V2_CONTRACT_VERSION: u32 = 2;
pub const COMMAND_CONTRACT_VERSION: u32 = 26;
