//! Selected dungeon frames, shared material vocabulary and exact paired routes.
use super::*;
const CLASSES: &[TileClass] = &[
    base("expedition_altar", false),
    base("expedition_chasm", true),
    base("expedition_dark_floor", false),
    base("expedition_dirt", false),
    class(
        "expedition_doorway_closed",
        TileRole::Door {
            open: false,
            hidden: false,
        },
    ),
    class(
        "expedition_doorway_open",
        TileRole::Door {
            open: true,
            hidden: false,
        },
    ),
    base("expedition_dungeon_water", false),
    base("expedition_fire_floor", false),
    base("expedition_floor", false),
    base("expedition_frozen_floor", false),
    base("expedition_grass", false),
    class(
        "expedition_masonry",
        TileRole::Door {
            open: false,
            hidden: true,
        },
    ),
    base("expedition_pillar", true),
    base("expedition_pit", true),
    base("expedition_portal", false),
    base("expedition_portcullis", true),
    base("expedition_rubble", false),
    base("expedition_stairs_down", false),
    base("expedition_stairs_up", false),
    base("expedition_tiled_floor", false),
    base("expedition_tree", true),
    base("expedition_wall", true),
    base("expedition_wooden_floor", false),
    class("expedition_path", TileRole::Route),
    class("expedition_footprint", TileRole::Footprint),
    class("expedition_mark", TileRole::Mark),
    class(
        "expedition_blocked",
        TileRole::Passability { walkable: false },
    ),
    class(
        "expedition_walkable",
        TileRole::Passability { walkable: true },
    ),
];
pub(super) const D1_ENTRY: MemberContract = MemberContract {
    id: "d1_entry",
    document: "content/lands/first-expedition/d1_entry.tmj",
    width: 36,
    height: 43,
    classes: CLASSES,
    tile_layers: &[
        "base_terrain",
        "routes",
        "structure_footprints",
        "landmark_marks",
        "passability",
    ],
    object_layers: &["structures", "transitions", "landmarks"],
    map_properties: MAP_PROPERTIES,
    structures: &[],
    landmarks: &[
        LandmarkContract {
            id: "reserved_surface_exit",
            role: "reserved_surface_exit",
            marker_class: "",
        },
        LandmarkContract {
            id: "deferred_access_01",
            role: "deferred_access",
            marker_class: "",
        },
        LandmarkContract {
            id: "deferred_access_02",
            role: "deferred_access",
            marker_class: "",
        },
        LandmarkContract {
            id: "deferred_access_03",
            role: "deferred_access",
            marker_class: "",
        },
        LandmarkContract {
            id: "deferred_access_04",
            role: "deferred_access",
            marker_class: "",
        },
        LandmarkContract {
            id: "deferred_access_05",
            role: "deferred_access",
            marker_class: "",
        },
        LandmarkContract {
            id: "deferred_access_06",
            role: "deferred_access",
            marker_class: "",
        },
        LandmarkContract {
            id: "deferred_access_07",
            role: "deferred_access",
            marker_class: "",
        },
        LandmarkContract {
            id: "deferred_access_08",
            role: "deferred_access",
            marker_class: "",
        },
        LandmarkContract {
            id: "deferred_access_09",
            role: "deferred_access",
            marker_class: "",
        },
        LandmarkContract {
            id: "deferred_access_10",
            role: "deferred_access",
            marker_class: "",
        },
    ],
    transitions: &[
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d1_entry_to_temple",
            target_member: "temple",
            paired_transition: "temple_to_d1_entry",
            direction: "up",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d1_entry_to_d2_stair_1",
            target_member: "d2",
            paired_transition: "d2_to_d1_entry_stair_1",
            direction: "down",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d1_entry_to_d2_stair_2",
            target_member: "d2",
            paired_transition: "d2_to_d1_entry_stair_2",
            direction: "down",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d1_entry_to_d2_stair_3",
            target_member: "d2",
            paired_transition: "d2_to_d1_entry_stair_3",
            direction: "down",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d1_entry_to_d2_guild",
            target_member: "d2",
            paired_transition: "d2_to_d1_entry_guild",
            direction: "passage",
            marker_class: "",
        },
    ],
    clustered_ground_class: None,
    wall_terrain_ids: &["expedition_wall", "expedition_tree", "expedition_pillar"],
    presentation: LevelPresentation {
        scene_role: SceneRoleDef::Interior,
        presentation_mode: PresentationModeDef::OverworldTown,
        law_zone: LawZoneDef::None,
        world_zoom: WorldZoomDef {
            screen_cell_pitch: [156, 104],
        },
        staged_viewport: Some(StagedViewportDef {
            frame_size: [1920, 1080],
            fit_whole_level: false,
        }),
    },
    candidate_entry: false,
};
pub(super) const D2: MemberContract = MemberContract {
    id: "d2",
    document: "content/lands/first-expedition/d2.tmj",
    width: 38,
    height: 43,
    classes: CLASSES,
    tile_layers: &[
        "base_terrain",
        "routes",
        "structure_footprints",
        "landmark_marks",
        "passability",
    ],
    object_layers: &["structures", "transitions", "landmarks"],
    map_properties: MAP_PROPERTIES,
    structures: &[],
    landmarks: &[
        LandmarkContract {
            id: "reserved_surface_exit",
            role: "reserved_surface_exit",
            marker_class: "",
        },
        LandmarkContract {
            id: "reserved_external_portal",
            role: "reserved_external_portal",
            marker_class: "",
        },
        LandmarkContract {
            id: "deferred_access_01",
            role: "deferred_access",
            marker_class: "",
        },
        LandmarkContract {
            id: "deferred_access_02",
            role: "deferred_access",
            marker_class: "",
        },
        LandmarkContract {
            id: "deferred_access_03",
            role: "deferred_access",
            marker_class: "",
        },
        LandmarkContract {
            id: "deferred_access_04",
            role: "deferred_access",
            marker_class: "",
        },
        LandmarkContract {
            id: "deferred_access_05",
            role: "deferred_access",
            marker_class: "",
        },
    ],
    transitions: &[
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d2_to_d1_entry_stair_1",
            target_member: "d1_entry",
            paired_transition: "d1_entry_to_d2_stair_1",
            direction: "up",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d2_to_d1_entry_stair_2",
            target_member: "d1_entry",
            paired_transition: "d1_entry_to_d2_stair_2",
            direction: "up",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d2_to_d1_entry_stair_3",
            target_member: "d1_entry",
            paired_transition: "d1_entry_to_d2_stair_3",
            direction: "up",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d2_to_d3_stair_1",
            target_member: "d3",
            paired_transition: "d3_to_d2_stair_1",
            direction: "down",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d2_to_d3_stair_2",
            target_member: "d3",
            paired_transition: "d3_to_d2_stair_2",
            direction: "down",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d2_to_d3_stair_3",
            target_member: "d3",
            paired_transition: "d3_to_d2_stair_3",
            direction: "down",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d2_to_d3_stair_4",
            target_member: "d3",
            paired_transition: "d3_to_d2_stair_4",
            direction: "down",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d2_to_d3_stair_5",
            target_member: "d3",
            paired_transition: "d3_to_d2_stair_5",
            direction: "down",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d2_to_d1_entry_guild",
            target_member: "d1_entry",
            paired_transition: "d1_entry_to_d2_guild",
            direction: "passage",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d2_to_d3_grand_8",
            target_member: "d3",
            paired_transition: "d3_to_d2_grand_8",
            direction: "door",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d2_to_d3_grand_9",
            target_member: "d3",
            paired_transition: "d3_to_d2_grand_9",
            direction: "door",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d2_to_d3_lake",
            target_member: "d3",
            paired_transition: "d3_to_d2_lake",
            direction: "passage",
            marker_class: "",
        },
    ],
    clustered_ground_class: None,
    wall_terrain_ids: &["expedition_wall", "expedition_tree", "expedition_pillar"],
    presentation: LevelPresentation {
        scene_role: SceneRoleDef::Interior,
        presentation_mode: PresentationModeDef::OverworldTown,
        law_zone: LawZoneDef::None,
        world_zoom: WorldZoomDef {
            screen_cell_pitch: [156, 104],
        },
        staged_viewport: Some(StagedViewportDef {
            frame_size: [1920, 1080],
            fit_whole_level: false,
        }),
    },
    candidate_entry: false,
};
pub(super) const D3: MemberContract = MemberContract {
    id: "d3",
    document: "content/lands/first-expedition/d3.tmj",
    width: 36,
    height: 43,
    classes: CLASSES,
    tile_layers: &[
        "base_terrain",
        "routes",
        "structure_footprints",
        "landmark_marks",
        "passability",
    ],
    object_layers: &["structures", "transitions", "landmarks"],
    map_properties: MAP_PROPERTIES,
    structures: &[],
    landmarks: &[
        LandmarkContract {
            id: "reserved_external_portal",
            role: "reserved_external_portal",
            marker_class: "",
        },
        LandmarkContract {
            id: "deferred_access_01",
            role: "deferred_access",
            marker_class: "",
        },
        LandmarkContract {
            id: "deferred_access_02",
            role: "deferred_access",
            marker_class: "",
        },
    ],
    transitions: &[
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d3_to_d2_stair_1",
            target_member: "d2",
            paired_transition: "d2_to_d3_stair_1",
            direction: "up",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d3_to_d2_stair_2",
            target_member: "d2",
            paired_transition: "d2_to_d3_stair_2",
            direction: "up",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d3_to_d2_stair_3",
            target_member: "d2",
            paired_transition: "d2_to_d3_stair_3",
            direction: "up",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d3_to_d2_stair_4",
            target_member: "d2",
            paired_transition: "d2_to_d3_stair_4",
            direction: "up",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d3_to_d2_stair_5",
            target_member: "d2",
            paired_transition: "d2_to_d3_stair_5",
            direction: "up",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d3_to_d4_stair_1",
            target_member: "d4",
            paired_transition: "d4_to_d3_stair_1",
            direction: "down",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d3_to_d4_stair_2",
            target_member: "d4",
            paired_transition: "d4_to_d3_stair_2",
            direction: "down",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d3_to_d4_stair_3",
            target_member: "d4",
            paired_transition: "d4_to_d3_stair_3",
            direction: "down",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d3_to_d2_grand_8",
            target_member: "d2",
            paired_transition: "d2_to_d3_grand_8",
            direction: "door",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d3_to_d2_grand_9",
            target_member: "d2",
            paired_transition: "d2_to_d3_grand_9",
            direction: "door",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d3_to_d2_lake",
            target_member: "d2",
            paired_transition: "d2_to_d3_lake",
            direction: "passage",
            marker_class: "",
        },
    ],
    clustered_ground_class: None,
    wall_terrain_ids: &["expedition_wall", "expedition_tree", "expedition_pillar"],
    presentation: LevelPresentation {
        scene_role: SceneRoleDef::Interior,
        presentation_mode: PresentationModeDef::OverworldTown,
        law_zone: LawZoneDef::None,
        world_zoom: WorldZoomDef {
            screen_cell_pitch: [156, 104],
        },
        staged_viewport: Some(StagedViewportDef {
            frame_size: [1920, 1080],
            fit_whole_level: false,
        }),
    },
    candidate_entry: false,
};
pub(super) const D4: MemberContract = MemberContract {
    id: "d4",
    document: "content/lands/first-expedition/d4.tmj",
    width: 37,
    height: 43,
    classes: CLASSES,
    tile_layers: &[
        "base_terrain",
        "routes",
        "structure_footprints",
        "landmark_marks",
        "passability",
    ],
    object_layers: &["structures", "transitions", "landmarks"],
    map_properties: MAP_PROPERTIES,
    structures: &[],
    landmarks: &[
        LandmarkContract {
            id: "reserved_external_portal",
            role: "reserved_external_portal",
            marker_class: "",
        },
        LandmarkContract {
            id: "deferred_access_01",
            role: "deferred_access",
            marker_class: "",
        },
        LandmarkContract {
            id: "deferred_access_02",
            role: "deferred_access",
            marker_class: "",
        },
    ],
    transitions: &[
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d4_to_d3_stair_1",
            target_member: "d3",
            paired_transition: "d3_to_d4_stair_1",
            direction: "up",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d4_to_d3_stair_2",
            target_member: "d3",
            paired_transition: "d3_to_d4_stair_2",
            direction: "up",
            marker_class: "",
        },
        TransitionContract {
            layout: TransitionLayout::Threshold,
            id: "d4_to_d3_stair_3",
            target_member: "d3",
            paired_transition: "d3_to_d4_stair_3",
            direction: "up",
            marker_class: "",
        },
    ],
    clustered_ground_class: None,
    wall_terrain_ids: &["expedition_wall", "expedition_tree", "expedition_pillar"],
    presentation: LevelPresentation {
        scene_role: SceneRoleDef::Interior,
        presentation_mode: PresentationModeDef::OverworldTown,
        law_zone: LawZoneDef::None,
        world_zoom: WorldZoomDef {
            screen_cell_pitch: [156, 104],
        },
        staged_viewport: Some(StagedViewportDef {
            frame_size: [1920, 1080],
            fit_whole_level: false,
        }),
    },
    candidate_entry: false,
};
